### ISSUE TITLE
Axis type and PPEM: "optical" or "parametric"

### ISSUE THREAD

**Issue by PeterCon** [Microsoft/OpenTypeDesignVariationAxisTags#16]
This past summer, John Hudson started using "optical" and "parametric" as terms to distinguish between different kinds of axes. The distinction seems useful for discussion of axes proposals, and so a field was added to the proposal summary template to specify an axis type: optical or parametric. 

See the [proposal summary template](https://github.com/Microsoft/OpenTypeDesignVariationAxisTags/blob/master/Proposals/ProposalSummary.md) for the descriptions of "optical" and "parametric".

The concept hasn't yet become conventional, though, and description of what "optical" and "parametric" mean leaves some room for subjective evaluation. So, for this reason, the field has been added to the General Technical Information section rather than the Proposed Axis Details section, as the info in the latter section would get added into the documentation in the registry if the proposal gets accepted.

Now we have a proposal for a PPEM axis, and the proposal summary has "optical" as the axis type. I'm wondering whether "parametric" wouldn't be more appropriate in this case.

So, I see two questions for discussion here:

- Is the current description in the proposal summary template for the optical/parametric axis distinction adequate, or could it use some refinement? (E.g., is the two-way distinction enough?)

- In the specific case of the proposed PPEM axis, which categorization is more appropriate: optical, or parametric?

**Comment by twardoch** [comment]
Do we have some sort of short summary of what "optical" and "parametric" mean?

**Comment by twardoch** [comment]
Found it in https://github.com/Microsoft/OpenTypeDesignVariationAxisTags/blob/master/Proposals/ProposalSummary.md

**Comment by twardoch** [comment]
Judging by the description, I think PPEM is definitely parametric. In a sense, it's the parametric counterpart to opsz, which is optical.

**Comment by dberlow** [comment]
"optical" and "parametric"  should perhaps have their own thread, unless this is to become typophile II. thanks

**Comment by PeterCon** [comment]
@Dberlow, please feel free to start a new thread (new issue) to discuss "optical" and "parametric".

**Comment by dberlow** [comment]
Oh, no thanks. I was just pointing out that this other topic was raised with no clear link to the facts of the matter.

**Comment by PeterCon** [comment]
I've edited my original post in this thread to add the reference to where "optical" and "parametric" are currently defined. I'm not sure if that's the missing facts you're referring to.

**Comment by tiroj** [comment]
@PeterCon

> Is the current description in the proposal summary template for the optical/parametric axis distinction adequate, or could it use some refinement? (E.g., is the two-way distinction enough?)

I believe the distinction is adequate, and does reflect the an essentially binary choice about how to _design_ a variable font: either allowing multiple axes to affect multiple aspects of glyph topography in multiple directions all at once (optical), or restricting each axis to affecting a specific aspect of glyph topography in a single direction (parametric). The terms 'optical' and 'parametric' don't obviously imply this distinction in all contexts and technologies, but I think they serve well enough with this definition for variable fonts.

Obviously — as I expressed when I saw you recently —, having a means to define the relationship of optical axis tags (as representing user controls) to parametric axes is a matter of some urgency.

> In the specific case of the proposed PPEM axis, which categorization is more appropriate: optical, or parametric?

I think the proposed PPEM axis is very clearly an example of an optical axis: the kinds of outline adjustments required to fit a glyph to a pixel grid involve both x and y direction movements of stems, stem weight adjustments, stem distance adjustments, and advance width adjustments. So that's a bunch of aspects of glyph topography. It is also easy to conceive how all those individual adjustments could be mapped on parametric axes — just as they can for e.g. Optical Size — and then, given an appropriate mechanism, accessed via PPEM as a higher level, optical axis tag.

**Comment by dberlow** [comment]
I'm not sure, well-named or not, binary choice or not — how is it useful to record the type designer's choice about whether they designed an axis effecting single or multiple variables?

In practice, I find tagging axes that change one thing and axes that change several, problematic because most of our "parametric" axes so far, have changed parameters in the opposite dimension, to satisfy the needs of the optical size at which those axes are targeted. So, for example, in a v-font with an opsz axis planned, the default style is some optical size. Then,  in our x transparency axis, (xtra), while the counters show a highly visible change of width, and as they do so, the overshoots and undershoots, branches, and other y-dimension parameters change for best results.

Also, is this an addition tag beside Show/Hide from UI, because they seem pretty similar in intent. Or is this just part of the proposal, so the reader of these can tell what's happening in an axis?

Last, I think a PPM axis exposes an issue, that the best information to tag an axis with, is information that helps users and applications determine what part of the type specification process an axis effects— in PPEM's case, it's is determined by the scaled output which, being after everything else a user chooses, has it's own particular programmatic and UI needs as a result. This optical/parametric tag doesn't seem to move in that direction.

**Comment by tiroj** [comment]
> Also, is this an addition tag beside Show/Hide from UI, because they seem pretty similar in intent. Or is this just part of the proposal, so the reader of these can tell what's happening in an axis?

It's just informational in the proposal, and isn't part of the axis specification that, when approved, would be incorporated into the registry. I suggested to Peter that it would be helpful to ask for this as an information point in proposals, since we're already looking at fonts with potential higher and lower level axes, with the possibility that some higher (optical) axes might constitute virtual or synthetic axes to access lower (parametric) axes. I think it is helpful, especially at this early stage, to ask proposers to think how their axis fits into such a framework (and if the response to that thinking is 'It doesn't' or 'The framework is inadequate', that's useful too).

Thanks very much for the example of y-direction adjustments on things like overshoots, branches, etc. in the XTRA axis. I don't think it fundamentally breaks my definition of parametric axes; rather, I'd look on those adjustments as something like free-riders: they contribute to the design-appropriate resolution of the x-transparency parameter, which is still fundamentally a single aspect of the design.

**Comment by PeterCon** [comment]
> Or is this just part of the proposal, so the reader of these can tell what's happening in an axis?

Yes, this is not a field in the description that would go into the registry. It's meant as a helpful guide to readers of the proposal to understand how the axis works.
